### ISSUE TITLE
i got this error when activate

### ISSUE THREAD

**Issue by mxmkmarquette** [ivankristianto/DB-Cache-Reloaded-Fix#5]
`DB Cache Reloaded Error: DB Module (wpdb class) is not loaded. Please open the Options Page, disable caching (remember to save options) and enable it again. If this will not help, please check FAQ how to do manual upgrade.`

**Comment by mxmkmarquette** [comment]
`Fatal error: Uncaught TypeError: Argument 2 passed to FWP_Register_Hook_Base_1x0x0::init() must be an instance of wpdb, instance of DBCR_WPDB_Wrapper given, called in /home/runcloud/webapps/madmax/wp-content/plugins/wp-external-links-disabled/libs/wprun/class-wprun-base.php on line 106 and defined in /home/runcloud/webapps/madmax/wp-content/plugins/wp-external-links-disabled/libs/fwp/component-bases/class-fwp-register-hook-base.php:30 Stack trace: #0 /home/runcloud/webapps/madmax/wp-content/plugins/wp-external-links-disabled/libs/wprun/class-wprun-base.php(106): FWP_Register_Hook_Base_1x0x0->init('/home/runcloud/...', Object(DBCR_WPDB_Wrapper)) #1 /home/runcloud/webapps/madmax/wp-content/plugins/wp-external-links-disabled/libs/wprun/class-wprun-base.php(83): WPRun_Base_1x0x0->__construct(Array) #2 /home/runcloud/webapps/madmax/wp-content/plugins/wp-external-links-disabled/wp-external-links.php(77): WPRun_Base_1x0x0::create('/home/runcloud/...', Object(DBCR_WPDB_Wrapper)) #3 /home/runcloud/webapps/madmax/wp-content/plugins in /home/runcloud/webapps/madmax/wp-content/plugins/wp-external-links-disabled/libs/fwp/component-bases/class-fwp-register-hook-base.php on line 30`

if i activate the other option.
